theme: jekyll-theme-cayman
title: Restauração de retratos por aprendizado de máquina
description: Projeto desenvolvido pelos alunos Lucas Hirano e Izabel Ferrari para conclusão do curso de Engenharia de Computação na Escola Politécnica da USP
